### ISSUE TITLE
Support Publishing via the Central Portal instead of legacy OSSRH

### ISSUE THREAD

**Issue by peteraraujo** [Kotlin/multiplatform-library-template#29]
Sonatype changed their publishing method for new artifacts and now it has to be done via the Central Portal. On their website, it says that [there is no official Gradle plugin yet but that we can use JReleaser, which does support the new method.](https://central.sonatype.org/publish/publish-portal-gradle/),

**Comment by ILIYANGERMANOV** [comment]
+1

**Comment by ZivStep** [comment]
+1

**Comment by ILIYANGERMANOV** [comment]
Fyi: I managed to fix it in https://github.com/Ivy-Apps/di

A few notes:
- key-id must be only the last 8 chars
- the key must be uploaded on a keyserver and its email verified

**Comment by pahill** [comment]
We have completely overhauled this and are addressing the issue now.

**Comment by atsushieno** [comment]
Can we see a proof of working publication on GitHub Actions ("Publish" workflow) ? I'm asking, because I keep failing to get it working, even with minimum changes from this template. For example: https://github.com/atsushieno/multiplatform-library-template-nexus-publisher/actions/runs/14990100091/job/42111980379

I'm seeing no attempt to actually run this workflow at https://github.com/Kotlin/multiplatform-library-template/actions/workflows/publish.yml .
